### PR TITLE
Wedesday morning with kon

### PR DESCRIPTION
**Pull request by saltedseacorn**
Final merge. Thank you all so much for the opportunity to grow and to learn with you all.

### CODE REVIEW

**Comment by lcpulzone** [comment]
Great job everyone!  Really fun working with all of you!!

**Review by gaelyn — APPROVED** [review]
Great job everyone! It's been fantastic working with you all!

**Review by lcpulzone — APPROVED** [review]
Woohoo!  Done!!

**Review by IcelandicGambit — APPROVED** [review]
See you space cowboy.

**Pull request merged**
